### ISSUE TITLE
Expose DB configuration settings

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream#100]
## Overview

There are currently 4 settings on `DB` and none of them are exposed via the configuration. They have reasonable defaults but it would be nice to make them adjustable if needed.

- `MonitorInterval`—How often the DB checks for WAL changes (defaults to `1s`)
- `CheckpointInterval`—How often the DB forces a new WAL (defaults to `1m`)
- `MinCheckpointPageN`—How many WAL pages before attempting a `PASSIVE` checkpoint (defaults to `1000`).
- `MaxCheckpointPageN`—How many WAL pages before forcing a `RESTART` checkpoint (defaults to `10,000`).

## Proposed Solution

Add these fields to the `DBConfig` type which would expose them in the YAML as:

```
dbs:
  - path: /path/to/db
    monitor-interval: 1s
    checkpoint-interval: 1m
    min-checkpoint-pages: 1000
    max-checkpoint-pages: 10000
```

It could be possible to move these to global settings as well if needed but that's not part of this initial implementation.
