### ISSUE TITLE
Global AWS Region Setting Broken?

### ISSUE THREAD

**Issue by cablespaghetti** [benbjohnson/litestream#107]
Hi,

Nothing major but with 0.3.2 and very restrictive S3 permissions, this config file worked:
```
addr: ":9090"
region: eu-west-1
dbs:
  - path: /db/db.db
    replicas:
      - url: s3://awsomebucket/db.db
```

However with the latest commit I get this error until I set the region for the specific replica:
```
addr: ":9090"
dbs:
  - path: /db/db.db
    replicas:
      - url: s3://awsomebucket/db.db
        region: eu-west-1
```

```
/db/db.db(s3): monitor error: cannot lookup bucket region: AccessDenied: Access Denied
	status code: 403, request id: ZHQP36T333JW5B5S, host id: 8zz0Z2/6VPrMJvWZBeXnBG5B5qRyCzrLLyBejUGFWuRceqNcCyTEy1Nk7vgN5WPTsIxNsJL+NGI=
```
