### ISSUE TITLE
Replication to Minio fails

### ISSUE THREAD

**Issue by lksnmnn** [benbjohnson/litestream#115]
Hi,

I am testing the 0.3.3 RC0 with a minio installation. Replication does not work and I get the following error (running as systemd service):

`monitor error: MissingRegion: could not find region configuration`

My config file:

```
access-key-id: <secret>
secret-access-key: <secret>

dbs:
  - path: /var/www/app/shared/db.sqlite
    replicas:
      - type: s3
        bucket: db-backup
        path: db.sqlite
        endpoint: https://<minio-domain>
        forcePathStyle: yes
        sync-interval: 1s
```

There error also occours, when I add and empty region `region: ''` to the config.

Cheers,
Lukas
