### ISSUE TITLE
Litestream restore from s3 bucket returns cannot restore wal: out of sequence wal segments

### ISSUE THREAD

**Issue by jdkdev** [benbjohnson/litestream#136]
When running `litestream restore /var/lib/sqlite.db` I get this error:

```
cannot restore wal: out of sequence wal segments: 20d8ec60b3a2ee6c/00000003 at remote offset 8272, expected offset 24752
```

It does seem to create a sqlite.db.tmp file that has partial data in it.

Here is my yml file:
```
access-key-id: <ID>....
secret-access-key: <KEY>...
dbs:
  - path: /var/lib/sqlite.db
    replicas:
      - type: s3
        bucket: sqlite-backups
        path: db 
        endpoint:  s3.us-west-000.backblazeb2.com
        force-path-style: true
```

### running litestream replicate
```
litestream v0.3.3
initialized db: /var/lib/sqlite.db
replicating to: name="s3" type="s3" bucket="sqlite-backups" path="db" region="" endpoint="s3.us-west-000.backblazeb2.com" sync-interval=10s
```

### running litestream wal /var/lib/sqlite.db
```
replica  generation        index  offset  size   created
s3       20d8ec60b3a2ee6c  0      0       487    2021-03-25T18:00:04Z
s3       20d8ec60b3a2ee6c  1      0       239    2021-03-25T18:02:43Z
s3       20d8ec60b3a2ee6c  2      0       250    2021-03-25T18:05:03Z
s3       20d8ec60b3a2ee6c  3      0       37754  2021-03-25T18:16:53Z
s3       20d8ec60b3a2ee6c  4      0       115    2021-03-25T18:43:56Z
```

### running litestream snapshots /var/lib/sqlite.db
```
replica  generation        index  size  created
s3       20d8ec60b3a2ee6c  0      230   2021-03-25T18:00:03Z
```

What would cause this issue?
