### ISSUE TITLE
Document how to configure Promethus exporter port.

### ISSUE THREAD

**Issue by dazzag24** [benbjohnson/litestream#16]
Thanks for opensourcing this project!

I have an existing Prometheus exporter on port 9090 so I need to change it.

```
❯ ./dist/litestream replicate -config ../litestream_testbed/config.yml
litestream (development build)
initialized db: /home/darreng/code/litestream_testbed/sourcedb/db.sqlite
replicating to: name="file" type="file" path="/home/darreng/code/litestream_testbed/replicadb/db.sqlite"
serving metrics on http://localhost:9090/metrics
cannot start metrics server: listen tcp :9090: bind: address already in use
```

I modified my config to include the "addr" setting and I was able to change the Prometheus metrics port.

```
addr: 0.0.0.0:9091
dbs:
  - path: /home/xxx/code/litestream_testbed/sourcedb/db.sqlite
    replicas:
      - path: /home/xxx/code/litestream_testbed/replicadb
```

Thanks

Darren
