### ISSUE TITLE
How to specify more than one replica in configuration file

### ISSUE THREAD

**Issue by hydra-yl** [benbjohnson/litestream#182]
What is the correct way to specify more than one s3 compatible replica in the configuration file? The following config will produce duplicate replica name "s3" error.

Thanks.

```
dbs:
  - path: /root/.metric.db
    replicas:
      - url: s3://mybkt/metric.db
        region: us-east-1
        endpoint: http://example.com:9000
        force-path-style: true
        access-key-id: minioadmin
        secret-access-key: minioadmin
        sync-interval: 1s
      - url: s3://mybkt2/metric.db
        region: us-east-1
        endpoint: http://example2.com:9000
        force-path-style: true
        access-key-id: minioadmin
        secret-access-key: minioadmin
        sync-interval: 1s
```

```
./litestream replicate -config /etc/litestream.yml
litestream (development build)
duplicate replica name: "s3"
```

**Comment by benbjohnson** [comment]
@hydra-yl Good question. Litestream automatically uses the type of replica for the name if no name is specified. 

It should work with something like:

```yaml
dbs:
  - path: /root/.metric.db
    replicas:
      - name: mybkt
        url: s3://mybkt/metric.db
        region: us-east-1
        endpoint: http://example.com:9000
        force-path-style: true
        access-key-id: minioadmin
        secret-access-key: minioadmin
        sync-interval: 1s
      - name: mybkt2
        url: s3://mybkt2/metric.db
        region: us-east-1
        endpoint: http://example2.com:9000
        force-path-style: true
        access-key-id: minioadmin
        secret-access-key: minioadmin
        sync-interval: 1s
```

I added a section to the docs to clarify: https://litestream.io/reference/config/#multiple-replicas
