### ISSUE TITLE
Support Filebase URLs

### ISSUE THREAD

**Issue by mtlynch** [benbjohnson/litestream#204]
I got a request for Filebase support in LogPaste so I'm passing it upstream to you:

https://github.com/mtlynch/logpaste/issues/114

Filebase does work if we define it explicitly:

```yaml
type: s3
endpoint: https://s3.filebase.com
bucket: mtl-test-bucket
path: .
```

So I think all that's required is [adding a parser](https://github.com/benbjohnson/litestream/blob/e4c1a82eb2fde5e60fd462691c51dbc3f6ef1d78/s3/s3.go#L1123) for Filebase URLs.

Filebase's only region is `us-east-1`:

https://docs.filebase.com/platform-overview/service-endpoints
