### ISSUE TITLE
Is oracle cloud storage (via S3 compatability) supported?

### ISSUE THREAD

**Issue by dazzag24** [benbjohnson/litestream#250]
Hi,

I have been experimenting with a ARM based Ampere instance in Oracle's always free tier:  https://www.oracle.com/cloud/free/?source=:ow:o:h:po:OHPPanel1nav0625&intcmp=:ow:o:h:po:OHPPanel1nav0625

the free tier also includes 10Gb of object storage which has an S3 compatibility layer: 
https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm

It offers these s3 compatible API calls: 
https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm#APIsupport

Has anyone tested if litestream works with it?

If not I may give it a go myself and feedback.

Thanks

Darren

**Comment by benbjohnson** [comment]
@dazzag24 I haven't tried Oracle's cloud storage option but I would think that it should work given the supported APIs. Litestream uses a fairly limited & basic set of S3 APIs (`GET`, `LIST`, `DELETE`). I'd be curious to hear how it works for you if you try it out.

**Comment by dazzag24** [comment]
I've not tested fully but the below seems to work on a arm64 ubuntu 20.04 instance. Generations folder structure with lz4 wal files appear in my bucket.

```
dbs:
  - path: /home/ubuntu/fruits.db
    replicas:
      - url: s3://<my_folder_name>/
        access-key-id: <access key>
        secret-access-key: <secret key>
        endpoint: https://<namespace>.compat.objectstorage.<region>.oraclecloud.com
        region: <region>   
```

Secret keys (needed for S3 compatability usage) creation is detailed here:  https://docs.oracle.com/en/cloud/paas/big-data-service/bdsmg/create-customer-secret-key.html

Namespaces and how to find them are documented here: https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/understandingnamespaces.htm
