### ISSUE TITLE
Build docker image multiarch (armv7, arm64)

### ISSUE THREAD

**Issue by ohthehugemanatee** [benbjohnson/litestream#310]
Love the project, it has made it possible to run a  lot of services on my k3s cluster! Thank you. 

Unfortunately the [docker image](https://hub.docker.com/r/litestream/litestream/tags) is only built for amd64, so it will only run on certain nodes.

If you haven't done it before, building container images cross platform is very easy. I would submit a PR if I could find the pipeline where you're doing it!  In a GitHub Actions workflow these are the relevant steps:

``` yaml
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: build the image and push
        run: |
          cd cluster/Dockerfiles/sidecar-sync && 
          docker buildx build \
          --push \
          --tag ghcr.io/${{ github.actor }}/sidecar-sync:multiarch \
          --platform linux/amd64,linux/arm64,linux/arm/v7 . 
```

You can see a complete example in [one of my own repos](https://github.com/ohthehugemanatee/homenet-documentation/blob/master/.github/workflows/build-sidecar-sync.yaml).
