### ISSUE TITLE
Cloudflare R2 support

### ISSUE THREAD

**Issue by ignoramous** [benbjohnson/litestream#372]
Cloudflare R2 is set to enter public beta [this week](https://archive.is/2u5Rt) (May 11 to be precise)!

[S3 API compatibility](https://developers.cloudflare.com/r2/platform/s3-compatibility/api/).

**Comment by benbjohnson** [comment]
Nice! Thanks for heads up. Hopefully it should "just work" with the existing S3 client but it'll be worth giving it a try.

**Comment by laiso** [comment]
It works with the existing S3 ReplicaClient. Wonderful!

```yaml
# litestream.yaml
dbs:
  - path: /var/lib/db
    replicas:
      - type: s3
        endpoint: https://MY_ACCOUNT_ID.r2.cloudflarestorage.com/
        bucket: MY_BUCKET_NAME
        access-key-id: MY_ACCESS_KEY
        secret-access-key: MY_SECRET_ACCESS_KEY
```

I can create Access key in R2 console:
https://developers.cloudflare.com/r2/platform/s3-compatibility/tokens/

**Comment by digizeph** [comment]
I'm seeing a lot of error messages when backing up a large sqlite3 file (about 8GB in size). 

```
May 21 23:54:57 peer-stat litestream[15832]: caused by: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your secret access key and signing method.
May 21 23:54:57 peer-stat litestream[15832]: #011status code: 403, request id: , host id:
```

**Comment by benbjohnson** [comment]
@digizeph The error looks like you don't have your access key & secret key set or they're incorrect:

```
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your secret access key and signing method.
```

You can set those in the config or you can use the `LITESTREAM_ACCESS_KEY_ID` and `LITESTREAM_SECRET_ACCESS_KEY` environment variables. https://litestream.io/reference/config/#s3-replica

**Comment by benbjohnson** [comment]
It looks like this is working well so far. I'm going to close the issue. If anyone has additional problems, please open a new issue.

**Comment by deadcoder0904** [comment]
Working example using Litestream: https://github.com/deadcoder0904/easypanel-nextjs-sqlite/

Turns out, if you are using Cloudflare R2 for other things like file storage (upload, download), then you can use Cloudflare R2's environment variables. Litestream uses the same keys. You can skip adding `access-key-id` & `secret-access-key` in `litestream.yml` if you use `LITESTREAM_ACCESS_KEY_ID` & `LITESTREAM_SECRET_ACCESS_KEY` but since I was using `CLOUDFLARE_R2_ACCESS_KEY_ID` & `CLOUDFLARE_R2_SECRET_ACCESS_KEY`, I had to add it.

This is my main project where I was using R2 for file storage.

### .env.example

```env
# Cloudflare R2 - File Storage
CLOUDFLARE_R2_ACCESS_KEY_ID=xxxx
CLOUDFLARE_R2_SECRET_ACCESS_KEY=xxxx
CLOUDFLARE_R2_BUCKET_NAME=xxx
CLOUDFLARE_R2_ACCOUNT_ID=xxxx
```

### litestream.yml

```yml
dbs:
  - path: /data/${SQLITE_DATABASE_NAME}
    replicas:
      - type: s3
        endpoint: https://${CLOUDFLARE_R2_ACCOUNT_ID}.r2.cloudflarestorage.com
        bucket: ${CLOUDFLARE_R2_BUCKET_NAME}
        access-key-id: ${CLOUDFLARE_R2_ACCESS_KEY_ID}
        secret-access-key: ${CLOUDFLARE_R2_SECRET_ACCESS_KEY}
```
