### ISSUE TITLE
flag provided but not defined: -v  in 0.4.0-beta2

### ISSUE THREAD

**Issue by ohthehugemanatee** [benbjohnson/litestream#386]
Running in kubernetes, so:

``` yaml
      initContainers:
        - name: init-litestream
          image: litestream/litestream:0.4.0-beta.2
          args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '/db/sonarr.db']
```

The command fails with `flag provided but not defined: -v`. The help message confirms that `-v` is for `verbose output`.
