### ISSUE TITLE
Update to 0.4.0-beta.2: no snapshots available on restore 

### ISSUE THREAD

**Issue by ohthehugemanatee** [benbjohnson/litestream#387]
I had an amd64 node die in my cluster and had to migrate some litestream-dependent workloads to arm64. Looks like there's no arm64 build of `0.3.8` available, so I had to run `0.4.0-beta.2` instead.

But on first run on the new node, the init container fails to restore. Apparently it can't see any replicas.

``` bash
#>  litestream restore /db/sonarr.db
cannot determine latest generation: generation time bounds: no snapshots available

#> litestream snapshots /db/sonarr.db
replica  generation  index  size  created
```

The backup directory has plenty of data:

``` bash
#> tree /db.backup/sonarr.db
/db.backup/sonarr.db
└── generations
    └── e7d6ea14e0477efe
        ├── snapshots
        │   └── 0001bd38.snapshot.lz4
        └── wal
            ├── 0001bd38_00000000.wal.lz4
            ├── 0001bd38_00000438.wal.lz4
            ├── 0001bd38_000049d0.wal.lz4
            ├── 0001bd38_00005618.wal.lz4
             ...
            ├── 0001bd98_00009380.wal.lz4
            └── 0001bd98_0000a7f8.wal.lz4

4 directories, 396 files

```

What am I missing?

**Comment by ohthehugemanatee** [comment]
I just tried with a 0.3.7 container running on amd64, and am having the same problem. So, what am I missing? The backup directory was generated with a sidecar container like this:

``` yaml

        - name: sonarr-litestream
          image: litestream/litestream:0.3.7
          args: ['replicate']
          volumeMounts:
          - name: sonarr-db
            mountPath: /db
          - name: nfs
            subPath: ".docker/config/sonarr/db-backup.litestream"
            mountPath: /db.backup
          - name: litestream-config
            mountPath: /etc/litestream.yml
            subPath: litestream.yml
```

litestream.yml:

``` yaml
dbs:
  - path: /db/sonarr.db
    replicas:
      - path: /db.backup/sonarr.db
```

Am I perhaps missing some other data file that gets stored outside of the replica directory?
