### ISSUE TITLE
x509 error

### ISSUE THREAD

**Issue by pettijohn** [benbjohnson/litestream#430]
I can't get any command to run, I always get an x509 certificate error. The error pasted below is from docker logs (replicate command), but I get the same error type for wal, snapshots, and generations commands. Seems like I have the pieces connected - it's 

Docker logs:

```
litestream v0.3.9
initialized db: /shares/app/Production.db
replicating to: name="s3" type="s3" bucket="litestream.mydomain.com" path="app-Production" region="us-east-1" endpoint="" sync-interval=1s
/shares/app/Production.db(s3): monitor error: RequestError: send request failed
caused by: Get "https://s3.amazonaws.com/litestream.mydomain.com?delimiter=%2F&prefix=app-Production%2Fgenerations%2F9cf0e13204b9330e%2Fsnapshots%2F": x509: certificate signed by unknown authority
```

_(Error repeating every second)_

./config/litestream.yml:

```
dbs:
  - path: /shares/app/Production.db
    replicas:
      - type: s3
        bucket: litestream.mydomain.com
        path: app-Production
        region: us-east-1
```

Launched from ./docker-compose.yml:

```
version: "3"
services:
  litestream:
    image: litestream/litestream
    volumes:
      - ./config:/etc
      - /shares:/shares
    env_file:
      - ./secrets/litestream-aws # sets LITESTREAM_ACCESS_KEY_ID and LITESTREAM_SECRET_ACCESS_KEY
    entrypoint:
      - /usr/local/bin/litestream
      - replicate
```

My hunch is I'm not getting the right S3 credentials to the service, but:

```
docker exec -it rclone_litestream_1 printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LITESTREAM_ACCESS_KEY_ID=<redacted>
LITESTREAM_SECRET_ACCESS_KEY=<redacted>
```

and those same credentials work with rclone in a different container. The IAM user has AmazonS3FullAccess.

**Comment by pettijohn** [comment]
One-liner docker run works...so there is something off with my compose approach above :-/

`docker run -v /shares:/shares -v config:/etc -e "LITESTREAM_ACCESS_KEY_ID=<redacted>" -e "LITESTREAM_SECRET_ACCESS_KEY=<redacted>" --rm -it litestream/litestream replicate /shares/app/Production.db s3://litestream.mydomain.com/app-Production`

**Comment by pettijohn** [comment]
When I move the access keys to an env-file, the command fails again.

`docker run --env-file secrets/litestream-aws -v /shares:/shares -v config:/etc -it litestream/litestream replicate /shares/app/Production.db s3://litestream.mydomain.com/app-Production`

```
litestream v0.3.9
initialized db: /shares/app/Production.db
replicating to: name="s3" type="s3" bucket="litestream.mydomain.com" path="app-Production" region="" endpoint="" sync-interval=1s
/shares/app/Production.db(s3): monitor error: cannot lookup bucket region: RequestError: send request failed
caused by: Get "https://s3.amazonaws.com/litestream.mydomain.com?location=": x509: certificate signed by unknown authority
^Csignal received, litestream shutting down
error closing db: path=/shares/app/Production.db err=cannot lookup bucket region: RequestError: send request failed
caused by: Get "https://s3.amazonaws.com/litestream.mydomain.com?location=": x509: certificate signed by unknown authority
litestream shut down
cannot lookup bucket region: RequestError: send request failed
caused by: Get "https://s3.amazonaws.com/litestream.mydomain.com?location=": x509: certificate signed by unknown authority
```

The approach seems to set environment variables correctly:

`docker run --env-file secrets/litestream-aws -v /shares:/shares -v ~/Code/HomeServerPi/rclone/config:/etc -it --entrypoint printenv litestream/litestream`

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=b7fc215f2c9e
TERM=xterm
LITESTREAM_ACCESS_KEY_ID=<redacted>
LITESTREAM_SECRET_ACCESS_KEY=<redacted>
HOME=/
```

I'm really stumped why passing environment variables with -e works but using -env-file doesn't.

**Comment by pettijohn** [comment]
I continue to be mystified here. I added `skip-verify: true` to the replica configuration, and it seems to work (at least it's not failing with an error right away). But it doesn't makes sense, and I shouldn't have to do that for public AWS S3. And why, without skip-verify, does it work in one case but not another?

**Comment by pettijohn** [comment]
Phew, I fixed it. I was mapping the volume `./config:/etc`, which blew away everything the Alpine base image had in `/etc`, including such _minor_ things like `/etc/ssl/certs/ca-certificates.crt which contains all of the trusted root CAs.` Fixed by mapping `./config/litestream.yml:/etc/litestream.yml` in docker-compose. What a rookie mistake! 🤦‍♂️

For reference, here is the working docker-compose.yml:

```
version: "3"
services:
  litestream:
    restart: always
    image: litestream/litestream
    volumes:
      - ./config/litestream.yml:/etc/litestream.yml
      - /shares:/shares
       # Important that the specific config file is mapped only - not all of /etc/** since that blows away /etc on the alpine image
    env_file:
      - ./secrets/litestream-aws
    entrypoint:
      - /usr/local/bin/litestream
      - replicate
```
