### ISSUE TITLE
Unable to recover database from a local replica

### ISSUE THREAD

**Issue by gustingonzalez** [benbjohnson/litestream#444]
Hi, there! I'm trying to recover a database by using the command `litestream restore -o /tmp/db /path/to/replica.db`. However, I'm getting the error `database not found in config:  /path/to/replica.db`. Also, I tried it without specifying the `-o` parameter, with same error. I can only recover the database without specifying the replica parameter.

Am I making a mistake specifying the command?

Thanks in advance!

**Comment by benbjohnson** [comment]
@gustingonzalez What does your config file look like?

**Comment by gustingonzalez** [comment]
@benbjohnson, my config file looks like the following:
```
# AWS credentials
# access-key-id:     AKIAxxxxxxxxxxxxxxxx
# secret-access-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxx

dbs:
  - path: /tmp/source.db            # Database to replicate from
    replicas:
      - path: /tmp/replica.db          # File-based replication

```
So, the command that I'm using is: `litestream restore -o /tmp/restored.db /tmp/replica.db`.

Note that, despite this, my understanding (according to the [documentation](https://litestream.io/reference/restore/#with-a-replica-url)) is that a config file wouldn't be required by using this command.

**Comment by benbjohnson** [comment]
@gustingonzalez If you're using a regular path then it'll try to match the database name. In that case, you'd need to specify:

```sh
$ litestream restore -o /tmp/restored.db /tmp/source.db
```

I believe you need to specify the replica in a URL format for it to skip the config:

```sh
$ litestream restore -o /tmp/restored.db file:///tmp/replica.db
```

**Comment by derpycoder** [comment]
I don't know why a path is required when we provide the config already.

```
dbs:
  - path: fruits.db
     replicas:
       - name: backblaze_backup
          type: s3
          bucket: litestream-damned-soul
          path: db
          endpoint: s3.us-east-005.backblazeb2.com
          force-path-style: true

       - name: local_backup
          path: ./backup/db/
```

```
litestream restore -config litestream.yml -replica local_backup -o ~/Linux/fruits2.db fruits.db
litestream restore -config litestream.yml -replica backblaze_backup -o ~/Linux/fruits2.db fruits.db
```

Without specifying the `fruits.db` at the end of the above commands, the backup was not working!
