### ISSUE TITLE
Replica URLs do not work for Scaleway object storage (S3)

### ISSUE THREAD

**Issue by schnz** [benbjohnson/litestream#498]
I was about to try litestream for the first time and was quite excited because the guide that describes to run it as a  docker container sidecar seemed easy enough to set it up in a matter of minutes. So I added the following service to my `compose.yml`:

```yml
services:
  litestream:
    image: litestream/litestream:0.3.11
    environment:
      - LITESTREAM_ACCESS_KEY_ID=<MyScalewayAccessKey>
      - LITESTREAM_SECRET_ACCESS_KEY=<MyScalewaySecret>
    volumes:
      - ./data:/data
    command: ["replicate", "/data/app.db", "s3://s3.nl-ams.scw.cloud/<mybucket>/<path-where-to-replicate-db-to>"]
```

Then my initial excitement came abruptly to an end as I realized that the S3 connection failed:

```txt
litestream v0.3.11
initialized db: /data/app.db
replicating to: name="s3" type="s3" bucket="s3.nl-ams.scw.cloud" path="<mybucket>/<path-where-to-replicate-db-to>" region="" endpoint="" sync-interval=1s
/data/app.db: sync: new generation "ad0981f58fcac748", no generation exists
/data/app.db(s3): monitor error: cannot lookup bucket region: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
status code: 403, request id: <redacted>, host id: <redacted>
```

Fortunately the error message is  quite detailed  and I assumed that the endpoint wasn't inferred correctly from the replica URL (judging from `endpoint=""`). I then searched the documentation for a list of supported environment variables in hope there would be something like `LITESTREAM_ENDPOINT` to manually set a custom S3 endpoint. Since I couldn't find a dedicated page that lists all environment variables I referred to the source code and [found the routine that is used to parse the replica URL](https://github.com/benbjohnson/litestream/blob/e0493f979a8269a53b83b35939d0820f0a3a4fc1/s3/replica_client.go#L696). 

By the looks of it ([see line 740 ongoing](https://github.com/benbjohnson/litestream/blob/e0493f979a8269a53b83b35939d0820f0a3a4fc1/s3/replica_client.go#L740)) there is a special treatment for some S3 providers, but Scaleway isn't one of them:

```go
var (
	localhostRegex    = regexp.MustCompile(`^(?:(.+)\.)?localhost$`)
	backblazeRegex    = regexp.MustCompile(`^(?:(.+)\.)?s3.([^.]+)\.backblazeb2.com$`)
	filebaseRegex     = regexp.MustCompile(`^(?:(.+)\.)?s3.filebase.com$`)
	digitalOceanRegex = regexp.MustCompile(`^(?:(.+)\.)?([^.]+)\.digitaloceanspaces.com$`)
	linodeRegex       = regexp.MustCompile(`^(?:(.+)\.)?([^.]+)\.linodeobjects.com$`)
)
```

Since Scaleway is the only provider that has a [dedicated section in the documentation](https://litestream.io/guides/scaleway/) but whose S3 URL isn't properly parsed, I am wondering if that is on purpose or was simply forgotten.
