### ISSUE TITLE
config location is omitted

### ISSUE THREAD

**Issue by nnWhisperer** [benbjohnson/litestream#590]
Hello,
When I prepare a yml file like the following, and run `litestream restore -config /home/user/litestream.yml`
/home/user/litestream.yml:
```
access-key-id: ${LITESTREAM_ACCESS_KEY}
secret-access-key: ${LITESTREAM_SECRET_KEY}

dbs:
  - path: ${LITESTREAM_MY_DB_PATH}
    replicas:
      - url: s3://my-backups/${LITESTREAM_S3_FOLDER_NAME}
        region: eu-west-3
```
I receive:
`ERROR failed to run error="database path or replica URL required"`
I must give:
litestream restore -o $LITESTREAM_MY_DB_PATH s3://my-backups/foldername/
