### ISSUE TITLE
Write Backblaze B2 guide

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream#68]

**Comment by mtlynch** [comment]
Here's a draft. Feel free to use wherever you'd like. I can submit as a PR to the docs repo if that's easier.

**Note**: Don't worry; the secret keys I show in the screenshot are for a throwaway user that I deleted immediately after.

**Note**: These instructions only work in the development version of litestream (specifically, v0.3.3-beta1-10-gf652186). They don't work with the v0.3.2 release.

## Create a bucket

1. Go to My Account > Buckets
1. Click "Create a Bucket"
1. Enter a unique name for "Bucket Unique Name" and leave the remaining fields as their defaults.
1. Click "Create a Bucket"
1. Copy the bucket details to the appropriate places in your `litestream.yml` file:

![image](https://user-images.githubusercontent.com/7783288/109387571-2721f680-78d0-11eb-9e3f-64badcc66e3f.png)

```yaml
dbs:
  - path: path-to-your-db-file
    replicas:
      - type: s3
        bucket: your-bucket-name
        endpoint: s3.us-west-000.backblazeb2.com # copy for your particular bucket
        region: us-west-000 # region is just the part after s3 in the endpoint above
```

## Create a user

1. Go to My Account > App Keys
1. Click "Add Application Key"
1. In "Name of Key" enter any unique name
1. Under "Allow access to Bucket(s)" select the bucket you created above.
1. Leave the remaining fields as their defaults.
1. Click "Create new key"
1. Copy the credentials to the appropriate places in your `litestream.yml` file
    * The `keyID` field is your `access-key-id`
    * The `applicationKey` field is your `secret-access-key`

![image](https://user-images.githubusercontent.com/7783288/109387588-3e60e400-78d0-11eb-9085-4b56014edfc3.png)

```yaml
access-key-id: your-backblaze-keyID
secret-access-key: your-backblaze-applicationKey
```

## `litestream.yml`

Your final `litestream.yml` config file should look like this:

```yaml
access-key-id: your-backblaze-keyID
secret-access-key: your-backblaze-applicationKey

dbs:
  - path: path-to-your-db-file
    replicas:
      - type: s3
        bucket: your-bucket-name
        endpoint: s3.us-west-000.backblazeb2.com # copy for your particular bucket
        region: us-west-000 # region is just the part after s3 in the endpoint above
```
