### ISSUE TITLE
Write AWS S3 guide

### ISSUE THREAD

**Issue by benbjohnson** [benbjohnson/litestream#76]

**Comment by cariaso** [comment]
Perhaps useful info for the minimum policy, from my own ongoing attempts at minimizing
```
            Statement:
              - Effect: Allow
                Action:
                  - "s3:*"
                Resource:
                  - Fn::Join:
                    - ''
                    - - 'arn:aws:s3:::'
                      - 'mybucket'
                      - '/'
                      - 'mypath'
                      - '*'
              - Effect: Allow
                Action:
                  #- "s3:DeleteBucketPolicy"
                  #- "s3:DeleteObject"
                  #- "s3:DeleteObjectVersion"
                  - "s3:GetAccountPublicAccessBlock"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
                  - "s3:GetBucketNotification"
                  - "s3:GetBucketPolicy"
                  - "s3:GetBucketPolicyStatus"
                  - "s3:GetBucketPublicAccessBlock"
                  - "s3:GetBucketVersioning"
                  - "s3:GetObject"
                  - "s3:GetObjectAcl"
                  - "s3:GetObjectTagging"
                  - "s3:GetObjectVersion"
                  - "s3:GetObjectVersionAcl"
                  - "s3:GetObjectVersionTagging"
                  - "s3:ListAllMyBuckets"
                  - "s3:ListBucket"
                  - "s3:ListBucketVersions"
                  #- "s3:PutBucketNotification"
                  #- "s3:PutBucketPolicy"
                  #- "s3:PutObject"
                  #- "s3:PutObjectAcl"
                  #- "s3:PutObjectTagging"
                  #- "s3:PutObjectVersionAcl"
                  #- "s3:PutObjectVersionTagging"
                Resource:
                  - Fn::Join:
                    - ''
                    - - 'arn:aws:s3:::'
                      - 'mybucket'
```

So far it seems functional with the '#' commented out actions, but I leave them in there for now as a possibly useful reminder.
